name: Python Hello World

on:
  push:
    branches:
      - master
  pull_request:
  
jobs:
  hello-python:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Run Hello World
      - name: Run Hello World script
        run: |
          echo "print('👋 Hello from Python inside GitHub Actions!')" > hello.py
          python hello.py
